baseurl: /cef-nominal-rolls
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "page"
    values:
      layout: "default"

page_list:
  Home: '/'
  About: '/about'
